name: unscroll
description: Minor project
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=2.18.2 <3.0.0'}
dependencies:
  flutter: {sdk: flutter}
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  get: ^4.6.5
  cached_network_image: ^3.2.2
  firebase_auth: ^3.11.2
  firebase_storage: ^10.3.11
  cloud_firestore: ^3.5.1
  image_picker: ^0.8.6
  salomon_bottom_bar: ^3.3.1
  video_compress: ^3.1.1
  modal_bottom_sheet: ^2.1.2
  timeago: ^3.3.0
  share_plus: ^6.0.1
  shimmer: ^2.0.0
  cached_video_player: ^2.0.3
  internet_connection_checker: ^1.0.0+1
  form_field_validator: ^1.1.0
  google_sign_in: ^5.4.2
  image_cropper: ^3.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  animated_splash_screen: ^1.3.0
  get_storage: ^2.0.3
  stop_watch_timer: ^2.0.0
  flutter_local_notifications: ^12.0.3+1
  firebase_messaging: ^13.1.0
  http: ^0.13.5
  connectivity_plus: ^3.0.2
  firebase_database: ^9.1.7
  image_downloader: ^0.31.0
  google_fonts: ^3.0.1
  uuid: ^3.0.7
  intl: ^0.17.0
  file_picker: ^5.2.2
  firebase_analytics: ^9.3.8
  firebase_crashlytics: ^2.9.0
  flutter_cache_manager: ^3.3.0
  story: ^0.8.0
  cloud_functions: ^3.3.9
  flutter_onboarding_slider: ^1.0.8
  flutter_spinkit: ^5.1.0







dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets: [assets/fonts/, assets/icon/, assets/images/]

