name: unscroll
description: Minor project
publish_to: none
version: 1.0.1+1
environment: {sdk: '>=2.18.2 <3.0.0'}
dependencies:
  flutter: {sdk: flutter}
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  get: ^4.6.5
  cached_network_image: ^3.2.2
  firebase_auth: ^4.2.0
  firebase_storage: ^11.0.7
  cloud_firestore: ^4.2.0
  image_picker: ^0.8.6
  video_compress: ^3.1.2
  modal_bottom_sheet: ^2.1.2
  timeago: ^3.3.0
  share_plus: ^6.3.0
  shimmer: ^2.0.0
  cached_video_player: ^2.0.3
  internet_connection_checker: ^1.0.0+1
  form_field_validator: ^1.1.0
  google_sign_in: ^5.4.2
  image_cropper: ^3.0.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  animated_splash_screen: ^1.3.0
  get_storage: ^2.0.3
  flutter_local_notifications: ^12.0.3+1
  firebase_messaging: ^14.1.4
  http: ^0.13.5
  connectivity_plus: ^3.0.2
  google_fonts: ^3.0.1
  uuid: ^3.0.7
  intl: ^0.17.0
  firebase_analytics: ^10.0.7
  firebase_crashlytics: ^3.0.7
  flutter_cache_manager: ^3.3.0
  story: ^0.8.0
  cloud_functions: ^4.0.6
  flutter_onboarding_slider: ^1.0.8
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15
  android_alarm_manager_plus: ^2.1.0
  palette_generator: ^0.3.3+2
  purchases_flutter: ^4.4.2
  url_launcher: ^6.1.7
  circular_countdown_timer: ^0.2.3
  flutter_easyloading: ^3.0.5
  firebase_core_platform_interface: 4.5.2
  gallery_saver: ^2.3.2
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  image_gallery_saver: ^1.7.1
  dio: ^4.0.6
  flutter_typeahead: ^4.1.1
  photo_view: ^0.14.0
  stories_editor: ^0.2.2












dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets: [assets/images/]

